build.gradle, src/main/java/com/teamharmony/newscommunity/NewsCommunityApplication.java, src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/users/dto/SignupDto.java, src/main/java/com/teamharmony/newscommunity/users/entity/Role.java, src/main/java/com/teamharmony/newscommunity/users/entity/RoleType.java, src/main/java/com/teamharmony/newscommunity/users/entity/Timestamped.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java, src/main/java/com/teamharmony/newscommunity/users/entity/UserRole.java, src/main/java/com/teamharmony/newscommunity/users/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/users/filter/CustomAuthorizationFilter.java, src/main/java/com/teamharmony/newscommunity/users/filter/SimpleCorsFilter.java, src/main/java/com/teamharmony/newscommunity/users/repo/RoleRepository.java, src/main/java/com/teamharmony/newscommunity/users/repo/UserRepository.java, src/main/java/com/teamharmony/newscommunity/users/repo/UserRoleRepository.java, src/main/java/com/teamharmony/newscommunity/users/security/AuthConstants.java, src/main/java/com/teamharmony/newscommunity/users/security/SecurityConfig.java, src/main/java/com/teamharmony/newscommunity/users/security/WebMvcConfig.java, src/main/java/com/teamharmony/newscommunity/users/service/UserService.java, src/main/java/com/teamharmony/newscommunity/users/service/UserServiceImpl.java, src/main/resources/application.properties
- 도메인 추가
- library 추가
- 로그 설정 추가
=> Add: add a user domain

src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/dto/responseDTO/ResponseNewsDetailDTO.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java, src/main/java/com/teamharmony/newscommunity/users/filter/SimpleCorsFilter.java, src/main/java/com/teamharmony/newscommunity/users/security/SecurityConfig.java
- 로컬 테스팅 환경에 맞춰 Cors, filter 수정
- detail 정보를 리턴해주는 controller, service 추가
=> Develop <- feature-provideNewsDetails

build.gradle, src/main/java/com/teamharmony/newscommunity/users/config/AmazonConfig.java, src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/users/dto/ProfileVO.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java, src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java, src/main/java/com/teamharmony/newscommunity/users/filesotre/FileStore.java, src/main/java/com/teamharmony/newscommunity/users/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/users/filter/SimpleCorsFilter.java, src/main/java/com/teamharmony/newscommunity/users/repo/UserProfileRepository.java, src/main/java/com/teamharmony/newscommunity/users/service/UserService.java, src/main/java/com/teamharmony/newscommunity/users/service/UserServiceImpl.java, src/main/resources/application.properties
=> Feat: 프로필 업데이트 기능 구현

src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java, src/main/java/com/teamharmony/newscommunity/comments/entity/Comment.java, src/main/java/com/teamharmony/newscommunity/comments/entity/Likes.java, src/main/java/com/teamharmony/newscommunity/comments/repository/LikesRepository.java, src/main/java/com/teamharmony/newscommunity/comments/service/LikesService.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsTable.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java
=> Feat: 좋아요 기능 구현

src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsTable.java, src/main/java/com/teamharmony/newscommunity/news/repository/NewsRepository.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java
- 뉴스 도메인에서 뉴스 정보 조회 관련 주석 수정 (Controller, Service, Repository)
- NewsTable 엔티티에 조회수를 위한 view 속성 추가
=> Merge: develop <- feature-newsDomainFIX

src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsTable.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java
**[FEAT]**
- 조회수 업데이트를 위한 컨트롤러, 서비스 계층의 메서드 작성
- 조회수 업데이트를 위해 Repository에 updateview 함수 추가
<br>
**[DOCS]**
- DOCS, FIX: view에 대한 주석이 작성 시간으로 잘못 표기되어있어, 이를 조회수로 변경
=> 😀Merge: develop <- feature-addViews

src/main/java/com/teamharmony/newscommunity/news/dto/responseDTO/ResponseNewsDetailDTO.java, src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
<br>
- 뉴스 정보 조회를 위한 getNews, getNewsDetail에 대한 테스트 코드 작성
- 뉴스 조회수 증가를 위한 addView에 대한 테스트 코드 작성
=> 😀Merge: develop <- feature-newsListingAndAddView(#33) 

src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java, src/main/java/com/teamharmony/newscommunity/bookmarks/dto/RequestBookmarkDTO.java, src/main/java/com/teamharmony/newscommunity/bookmarks/dto/ResponseBookmarkDTO.java, src/main/java/com/teamharmony/newscommunity/bookmarks/entity/Bookmarks.java, src/main/java/com/teamharmony/newscommunity/bookmarks/repository/BookmarkRepository.java, src/main/java/com/teamharmony/newscommunity/bookmarks/service/BookmarkService.java, src/main/java/com/teamharmony/newscommunity/bookmarks/util/TimestampedOnBookmark.java, src/main/java/com/teamharmony/newscommunity/comments/common/ApiResponse.java, src/main/java/com/teamharmony/newscommunity/comments/common/ApiResponseHeader.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/users/security/SecurityConfig.java, src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java
<br>
- 북마크 생성
- 북마크 검증
- 북마크 취소
- 북마크 조회 (특정 유저의)
=> 😀Merge: develop <- feature-bookmarkService

src/main/java/com/teamharmony/newscommunity/supports/controller/SupportController.java, src/main/java/com/teamharmony/newscommunity/supports/dto/SupportRequestDto.java, src/main/java/com/teamharmony/newscommunity/supports/entity/Support.java, src/main/java/com/teamharmony/newscommunity/supports/repository/SupportRepository.java, src/main/java/com/teamharmony/newscommunity/supports/service/SupportService.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java
기존 기본 CRUD 구현에서, 로그인된 User 정보를 반영해서 객체 생성하도록 함.
=> Feat: 고객관리 객체 생성시 User 정보 반영

build.gradle, src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/users/dto/ProfileVO.java, src/main/java/com/teamharmony/newscommunity/users/dto/SignupDto.java, src/main/java/com/teamharmony/newscommunity/users/entity/Role.java, src/main/java/com/teamharmony/newscommunity/users/entity/Tokens.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java, src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java, src/main/java/com/teamharmony/newscommunity/users/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/users/service/UserService.java, src/main/java/com/teamharmony/newscommunity/users/service/UserServiceImpl.java, src/main/resources/application.properties
=> 회원 도메인 리팩토링, 주석 추가

src/main/java/com/teamharmony/newscommunity/users/filter/CustomAuthorizationFilter.java, src/main/java/com/teamharmony/newscommunity/users/security/SecurityConfig.java
=> Fix: 고객관리 페이지 모든 사람 열람 가능

src/main/java/com/teamharmony/newscommunity/NewsCommunityApplication.java, src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java, src/main/java/com/teamharmony/newscommunity/bookmarks/entity/Bookmarks.java, src/main/java/com/teamharmony/newscommunity/common/ApiResponse.java, src/main/java/com/teamharmony/newscommunity/common/ApiResponseHeader.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/dto/requestCreateDTO/RequestCreateNewsAccessLogDTO.java, src/main/java/com/teamharmony/newscommunity/news/dto/responseDTO/ResponseNewsDTO.java, src/main/java/com/teamharmony/newscommunity/news/dto/responseDTO/ResponseNewsDetailDTO.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsAccessLog.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsTable.java, src/main/java/com/teamharmony/newscommunity/news/repository/NewsAccessLogRepository.java, src/main/java/com/teamharmony/newscommunity/news/repository/NewsRepository.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java, src/main/java/com/teamharmony/newscommunity/news/util/TimestampedOnLog.java, src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java
=> Merge: develop <- feature-applyJavadoc

src/main/java/com/teamharmony/newscommunity/bookmarks/entity/Bookmarks.java, src/main/java/com/teamharmony/newscommunity/bookmarks/entity/TimestampedOnBookmark.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/dto/RequestCreateNewsAccessLogDTO.java, src/main/java/com/teamharmony/newscommunity/news/dto/ResponseNewsDTO.java, src/main/java/com/teamharmony/newscommunity/news/dto/ResponseNewsDetailDTO.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsAccessLog.java, src/main/java/com/teamharmony/newscommunity/news/entity/TimestampedOnLog.java, src/main/java/com/teamharmony/newscommunity/news/repository/NewsAccessLogRepository.java, src/main/java/com/teamharmony/newscommunity/news/repository/NewsRepository.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java, src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java, src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
- DOC:#42 코드 구조 통일을 위한 디렉토리 변경
=> Merge: develop <- feature-news

src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
[Feat]
- username으로 프로필 사진 url 조회하는 기능 구현
<br/> 
[Fix]
- 기존 함수에 매개변수를 줄이면서 수정이 필요한 부분 해결
<br/> 
Fixed: #74
=>  프로필 사진 url 조회 기능 구현

src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java, src/main/java/com/teamharmony/newscommunity/exception/Error.java, src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
[Refactor]
북마크 생성 로직의 builder 패턴 정확하게 적용
#Fixed: #96
=> 예외처리 로직에 대한 필드값 수정 및 빌더 패턴 적용

src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java, src/main/java/com/teamharmony/newscommunity/bookmarks/dto/ResponseBookmarkDTO.java, src/main/java/com/teamharmony/newscommunity/bookmarks/service/BookmarkService.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/dto/ResponseNewsDetailDTO.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java, src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
[Refactor] 
- stream을 이용해 dto에 리스트 값을 넘겨주는 형태에서 리스트 형태의 dto를 만드는 형태로 변경 (북마크 도메인)
- stream을 이용해 dto에 리스트 값을 넘겨주는 형태에서 리스트 형태의 dto를 만드는 형태로 변경 (뉴스 도메인)
Fixed: #99
=> stream을 이용해 dto에 리스트 값을 넘겨주는 형태에서 리스트 형태의 dto를 만드는 형태로 변경

src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java, src/main/java/com/teamharmony/newscommunity/bookmarks/dto/BookmarkRequestDto.java, src/main/java/com/teamharmony/newscommunity/bookmarks/dto/BookmarkResponseDto.java, src/main/java/com/teamharmony/newscommunity/bookmarks/entity/Bookmarks.java, src/main/java/com/teamharmony/newscommunity/bookmarks/service/BookmarkService.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java, src/main/java/com/teamharmony/newscommunity/news/dto/CreateNewsAccessLogRequestDto.java, src/main/java/com/teamharmony/newscommunity/news/dto/NewsDetailResponseDto.java, src/main/java/com/teamharmony/newscommunity/news/dto/NewsResponseDto.java, src/main/java/com/teamharmony/newscommunity/news/entity/NewsAccessLog.java, src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java, src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java, src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
[Refactor] 
- 다른 도메인과 다른 네이밍 형식 1 해결 (DTO -> Dto)
- 다른 도메인과 다른 네이밍 형식 2 해결 (RequestTaregetDto -> TaregetRequestDto)
Fixed: #101
=> 다른 도메인과 다른 뉴스 도메인과 북마크 도메인의 DTO 네이밍 형식 통일

src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
[Fix]
쿠키 유효 시간 ms로 생각하고 *1000 했던 부분 수정
Fixed:  #106
=> 쿠키 유효 시간 수정

src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
댓글과 관련하여 잘못된 요청에 대하여 예외처리를 추가해보았습니다.
요청 URL이 잘못된 부분에 대해서는 아예 컨트롤러에서 매핑이 되지 않는다고 튜터님께서 말씀하셔서 제외하였습니다. 
Fixed: #95
=> Feat: 잘못된 요청에 대한 예외처리

src/main/java/com/teamharmony/newscommunity/comments/entity/Timestamped.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
=> Refactor: 불필요한 주석 제거 

src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java, src/main/java/com/teamharmony/newscommunity/news/controller/NewsController.java
[Refactor]
- Refactor: 북마크 도메인의 Response 형식 ApiResponse-> ResponseEntity로 변경
- Refactor: 뉴스 도메인의 Response 형식 ApiResponse-> ResponseEntity로 변경
fixed: #45
=> 뉴스, 북마크 도메인 response 형식 통일

src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
: 장형철 튜터님에게 자문을 구했을 때, stacktrace를 남겨주면 좋을 것 같다는 피드백을 받아
<br>
<br>
: 에러를 전역적으로 핸들링하는 GlobalHandlerException에서 에러에 대한 message와 stacktrace를 slf4j를 통해 기록토록 함
<br>
Fixed: #126 
<br>
`Merge: develop <- `126/feat_add-stacktrace-message #127
=> Feat: 해당 에러에 대한 message와 stack trace를 log로 작성

src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java, src/main/resources/logback.xml
: logback 생성을 위한 xml 작성 및 Aop를 통한 parameter 로깅기능 추가
<br>
<br>
: 로깅에 들어갔으면 하는 값, 사용자 id를 시큐리티에서 어떻게 받아올지 방법 정의
<br>
Fixed: #130
<br>
`Merge: develop <- 130/feat_aop-log #131
=> Feat: logback 생성을 위한 xml 작성 및 Aop를 통한 parameter 로깅

.gitignore
: 깃허브에 굳이 올릴 필요가 없는 application_log 디렉토리를 아예 .gitignore 파일에 추가했습니다.
<br>
<br>
: 없습니다.
<br>
Fixed: #138 
<br>
=> Doc: .gitignore에 application_log 디렉토리 추가 

src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java, src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
: 갱신 토큰이 저장된 쿠키가 있는지 따로 확인하지 않도록 하고 해당 함수의 실행 결과가 반환되도록 수정
<br>
<br>
:
<br>
Fixed: #140
<br>
`Merge: develop <- `140/bug_sign-out #141
=> 로그아웃 후 로그인 시도 시 자동 재로그인되는 오류 수정

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: List의 사이즈를 통해 얻는 방식에서 새로운 쿼리메소드를 통해 얻는 방식으로 수정
<br>
<br>
:
<br>
Fixed: #142 
<br>
=> 댓글 개수를 얻는 방식 수정

.github/workflows/main.yml, src/test/java/com/teamharmony/newscommunity/NewsCommunityApplicationTests.java
: 현재 배포시 발생하는 에러는, 테스트 코드에 의한 에러와 yml상의 application 환경 명의 잘못된 기재로 발생한것으로 보임.
이를 해결하기 위해 1차적으로 해당 구문들을 수정함
<br>
<br>
: 특이사항 없음
<br>
Fixed: #143
<br>
`Merge: develop <- 143/fix_cicd-rebuilds #144
=> 배포문제 1차 해결

src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java, src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java, src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java, src/main/java/com/teamharmony/newscommunity/auth/util/CookieUtil.java, src/main/java/com/teamharmony/newscommunity/exception/TokenException.java
- 예외 발생 시 반환되는 헤더에 쿠키 제거를 넣기 위해서 기존 함수 수정 https://github.com/2022-Harmony/NewsCommunity-bFinal/pull/148/commits/1d385134a39e6846a3cd38e104754f58d04d9269
- 토큰 갱신하는 과정에서 발생하는 예외 처리를 위한 커스텀 예외 클래스 생성 https://github.com/2022-Harmony/NewsCommunity-bFinal/pull/148/commits/9dc5d459fc3a91dae3a50ace9a8ac311b53d5bda
- 전전커밋으로 인해 수정이 필요해진 연관 함수 수정 https://github.com/2022-Harmony/NewsCommunity-bFinal/pull/148/commits/b66d4344bce1993676881393604c2a5eaf103f10
- 토큰 갱신에서 호출하는 함수(허용 토큰 정보 조회, 쿠키 조회)에 throws 붙여주고 갱신 과정에서 발생하는 함수 잡아내기 https://github.com/2022-Harmony/NewsCommunity-bFinal/pull/148/commits/3598a769dd69e58e2ee961b418a068c63bbab4a0
- illegal~ 로 처리했던 예외 수정 https://github.com/2022-Harmony/NewsCommunity-bFinal/pull/148/commits/8c2feeca260062533f7a0792336a6801ddb9c51b
<br>
<br>
: 필터 쪽은 따로 하겠습니다ㅠ
<br> …
=> auth 패키지 예외 처리(필터 제외)

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
- 페이징 구현을 위해 controller, repository, service를 수정했습니다.
- 그런데 아마 이 코드로만은 화면에서 댓글이 안 보일텐데 그건 security쪽에서 /api/comments를 열어주면 될 것 같습니다.
<br>
<br>
:
<br>
Fixed: #129 
<br>
=> 뉴스 상세페이지 댓글 페이징 구현

src/main/java/com/teamharmony/newscommunity/users/dto/SignupRequestDto.java
: 중복 체크 때 쓸 dto 생성 / 적용은 프론트 타입 바꾸고 어노테이션 수정하면서 할게요
<br>
<br>
:
<br>
Fixed: 아직 해결 중
<br>
`Merge: develop <- `44/feat_add-dto #pr번호
=> 회원 가입 시 ID 중복 체크를 위한 Dto 내부 클래스 생성

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 프로필 페이지 댓글 페이징 기능입니다.
<br>
<br>
:
<br>
Fixed: #153  
<br>
=> 프로필 페이지 댓글 페이징 기능

src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
: 회원 가입 중복 체크 경로 누락 수정
config에 /api/signup ->/api/signup/**
<br>
<br>
:
<br>
Fixed: #163
<br>
=> 회원 가입 중복 체크되지 않는 오류 수정

src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java, src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
: 기존 news 도메인의 DTO 생성 방식 변경으로 이에 맞춰 테스트 코드 수정 (동기화)
<br>
<br>
: 객체 생성 방식과 같이 여러 클래스에 영향을 주는 변경은 테스트 코드의 변경도 확인해야함
<br>
Fixed: #147 
<br>
Merge: develop <- 147_test-code-sync #171
=> 테스트 코드 관련 에러 수정

src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthorizationFilter.java, src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java, src/main/resources/application.properties
- 토큰 갱신할 때 인가 필터를 거치면서 오류를 발생시켜 수정했습니다.
- 토큰을 갱신하고 접근 토큰을 로컬 스토리지에 다시 저장하면서 기존 로컬 스토리지가 날라가서 
username을 다시 넣어주도록  했습니다.
- 테스트를 위해 16시간으로 설정되어있던 토큰 유효시간을 줄였습니다.
- 토큰 생성에 필요한 비밀키를 환경 변수로 수정했습니다.
<br>
<br>
:
<br>
Fixed: #168 #169 #170 #172 
<br>
`Merge: develop <- `168/fix_refresh-token #pr번호
=> 토큰 갱신 관련 오류 수정 & 토큰 생성 비밀키 환경 변수 설정

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 좋아요 확인 로그인 사용자 기준으로 확인하도록 변경(프론트 변경 필요)
<br>
<br>
:
<br>
Fixed: #178
<br>
`Merge: develop <- `178/bug_check-like #pr번호
=> 좋아요 이력 확인 오류

src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java, src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthorizationFilter.java, src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 
<br>
<br>
:
<br>
Fixed: 
<br>
=> 시크릿 키 수정 & 좋아요 확인 비로그인 오류 수정

.github/workflows/main.yml
: 기존 develop로 되어있던 배포 브랜치를 main으로 변경
<br>
<br>
: CI/CD 배포 환경에 대한 인식
<br>
Fixed: #185
<br>
`Merge: develop <- `185/trans-deploy-branch-main #186
=> 배포 브랜치를 main으로 변경

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 댓글 개수보다 페이징 번호가 많이 나오는 부분을 수정했습니다.
<br>
<br>
:
<br>
Fixed: #190 
<br>
=> 프로필 페이지 댓글 페이징 번호 개선

src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java, src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
: 파라미터 추적시 로깅을 info가 아닌 error로 설정, 글로벌 exception시 logging을 안하고 sout을 했던 것을 수정
<br>
<br>
: exception에 대한 로깅 방식
<br>
Fixed: #193 
<br>
`Merge: develop <- `193/fix_loggin-fault #195
=> 미비된 로깅 부분 보수

src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java, src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java, src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/dto/CommentResponseDto.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 댓글 페이징 개선 기능과 로깅 관련 내용 Release
<br>
<br>
: 페이징 개선, 로깅 처리가 배포시 잘 적용이 되었는지
<br>
Fixed:  #196 
<br>
`Merge: main<- `develop #197
=> [Deploy] 2022-07-26 댓글 페이지 기능 개선, 로깅 미비 사항 개선 패치

src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java, src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
: 정렬기능 구현 방식 수정에 따른 기존 정렬 기능 구현을 위한 코드를 삭제했습니다.
<br>
<br>
:
<br>
Fixed: #192 
<br>
=> 기존 정렬 기능과 관련된 코드 삭제

src/main/java/com/teamharmony/newscommunity/supports/service/SupportService.java
: Dto 생성시 for문 사용에서 stream과 map 사용하는 것으로 변경함
<br>
<br>
:
<br>
Fixed: 166
<br>
=> Refactor: Dto 생성시 for문 사용에서 stream과 map 사용하는 것으로 변경 #166

src/main/resources/application.properties
: 로컬에서 프로필 변경이 가능한 버킷으로 수정했습니다.
<br>
<br>
:
<br>
Fixed: #200 
<br>
=> 프로필 변경이 가능한 버킷으로 환경 변수 수정

src/main/java/com/teamharmony/newscommunity/auth/entity/Tokens.java, src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/users/dto/ProfileResponseDto.java, src/main/java/com/teamharmony/newscommunity/users/dto/SignupRequestDto.java, src/main/java/com/teamharmony/newscommunity/users/dto/UserResponseDto.java, src/main/java/com/teamharmony/newscommunity/users/entity/Role.java, src/main/java/com/teamharmony/newscommunity/users/entity/User.java, src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java, src/main/java/com/teamharmony/newscommunity/users/entity/UserRole.java, src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
: @/Data 등 필요 이상의 어노테이션들을 제거하고 그로 인해 필요한 수정
+content-type 변경으로 인한 @/RequestBody 추가
<br>
<br>
:
<br>
Fixed: #149
<br>
=> users, auth패키지 어노테이션 수정

src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java, src/main/java/com/teamharmony/newscommunity/comments/service/LikesService.java
: 좋아요 여부를 확인해줄 API를 따로 만들어서 프론트엔드에서 사용하도록 했습니다.
<br>
<br>
:
<br>
Fixed: #208 
<br>
=> 좋아요 여부를 확인하는 과정 추가

src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
: 객체 삭제하는 코드 제거했습니다.
<br>
<br>
: 이것만 없애면 프로필 업데이트 기능이 잘 동작할까?
<br>
Fixed: #214
<br>
=> 프로필 업데이트 오류 해결

build.gradle
: 스웨거를 적용해보기 위해서 디펜던시를 추가함.
<br>
<br>
:
<br>
Fixed: #218 
<br>
=> 스웨거 적용 위한 디펜던시 추가

src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java, src/main/java/com/teamharmony/newscommunity/exception/Error.java, src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
- ErrorResponse 클래스에 있던 code와 message 필드를 Error 클래스로 옮김
- null일 때는 생략되도록 함
<br>
<br>
:
<br>
Fixed: #236
<br>
=> 예외 처리 관련 수정

src/main/java/com/teamharmony/newscommunity/config/SwaggerConfig.java, src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentCreateRequestDto.java, src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentEditRequestDto.java
: 일단 최소한으로 swagger를 적용해봤습니다. @ApiResponse는 정상적으로 되지 않아 일단 보류했습니다.
<br>
<br>
:
<br>
Fixed: #221 
<br>
=> comment swagger 적용

src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
: 생성자로 예외 처리하던 부분에 builder 사용
<br>
<br>
:
<br>
Fixed: #136
<br>
=> 예외 객체 생성 방식 변경

src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/service/CommentService.java, src/main/java/com/teamharmony/newscommunity/domain/comments/service/LikesService.java
:  comments 패키지의 CommentController, LikesController, CommentService, LikesService에 JavaDoc 추가
<br>
<br>
:
<br>
Fixed: #239 
<br>
=> Comment 패키지 JavaDoc 추가

src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java, src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentCreateRequestDto.java, src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentEditRequestDto.java, src/main/java/com/teamharmony/newscommunity/domain/comments/service/CommentService.java, src/main/java/com/teamharmony/newscommunity/domain/comments/service/LikesService.java
: 전반적인 코드 리팩토링
<br>
<br>
:
<br>
Fixed: #254 
<br>
=> 전반적인 코드 리팩토링

src/main/java/com/teamharmony/newscommunity/domain/users/controller/UserController.java, src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
- responseentity 201 상태 코드이던 부분들 200으로 통일
- aop로 로그 남기고 있으니 중복되는 로깅 삭제
- service에 회원 가입 함수 주석 추가
- 함수 순서 변경-controller랑 service랑 중구난방이어서
- 회원 가입 성공 시 success 반환하도록 변경하고 try catch 제거
<br>
<br>
:
<br>
Fixed: #162 
<br>
`Merge: develop <- `162/refactor/users_package #pr번호
=> users package 일부분 변경
